// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuopME2zr6E9JEJ8QS_4WyAECQL_5qiT8',
    appId: '1:738522198227:web:eb0c3002f350d0c59ae426',
    messagingSenderId: '738522198227',
    projectId: 'rrbikerental-e8507',
    authDomain: 'rrbikerental-e8507.firebaseapp.com',
    storageBucket: 'rrbikerental-e8507.firebasestorage.app',
    measurementId: 'G-M0X9V4RQ0D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCP0oBKa27GykeF-5kJpaSiDvUjqXWML9w',
    appId: '1:738522198227:android:8d3b9c4f4cb37d689ae426',
    messagingSenderId: '738522198227',
    projectId: 'rrbikerental-e8507',
    storageBucket: 'rrbikerental-e8507.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlu7ZU952UBHtI_V1ctNjj5M7AVJUvgnM',
    appId: '1:738522198227:ios:efdbe9dca31f6bcf9ae426',
    messagingSenderId: '738522198227',
    projectId: 'rrbikerental-e8507',
    storageBucket: 'rrbikerental-e8507.firebasestorage.app',
    iosBundleId: 'com.example.rrbikerental',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlu7ZU952UBHtI_V1ctNjj5M7AVJUvgnM',
    appId: '1:738522198227:ios:efdbe9dca31f6bcf9ae426',
    messagingSenderId: '738522198227',
    projectId: 'rrbikerental-e8507',
    storageBucket: 'rrbikerental-e8507.firebasestorage.app',
    iosBundleId: 'com.example.rrbikerental',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuopME2zr6E9JEJ8QS_4WyAECQL_5qiT8',
    appId: '1:738522198227:web:fd629ee6d17999369ae426',
    messagingSenderId: '738522198227',
    projectId: 'rrbikerental-e8507',
    authDomain: 'rrbikerental-e8507.firebaseapp.com',
    storageBucket: 'rrbikerental-e8507.firebasestorage.app',
    measurementId: 'G-SB2MVWJESC',
  );
}
